asset_management/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LoginPage, name="Login"),
    path('logout/', views.LogoutUser, name="Logout"),
    path('user/', include('users.urls')),
    path('master/', include('master.urls')),
    path('product/', include('product.urls')),
    path('dashboard/', views.Dashboard,name='Dashboard'),
]

product/urls.py
from django.urls import path
from users import views
from product import views

from .views import (SoftwareCreateView, SoftwareListView,
                    HardwareListView,SoftwareUpdateView,HardwareUpdateView,HardwareAssignView,
                    HardwareDetailView,AssignedAssetReportListView,UnAssignedAssetReportListView,
                    DisposedAssetListView,SoftwareInUseListView,SoftwareInStockListView,NonITAssetListView,
NonITAssetUpdateView,NonITAssetAssignView,
# UnAssignedView,
)

urlpatterns = [
    path('software', SoftwareCreateView.as_view(), name="SoftwareCreate"),
    path('software_list', SoftwareListView.as_view(), name="SoftwareList"),
    path('software/update/<int:pk>', SoftwareUpdateView.as_view(), name="SoftwareUpdate"),
    
    
    path('hardware', views.HardwareCreateView, name="HardwareCreate"),
    path('hardware_list', HardwareListView.as_view(), name="HardwareList"),
    path('hardware/update/<int:pk>', HardwareUpdateView.as_view(), name="HardwareUpdate"),
    # path('hardware/detail/<int:pk>', HardwareDetailView.as_view(), name="HardwareDetail"),
    path('hardware/detail/<int:pk>', views.HardwareDetailView, name="HardwareDetail"),
    path('hardware/assign/<int:pk>', HardwareAssignView.as_view(), name="HardwareAssign"),
    # path('hardware/return/<int:pk>', HardwareReturnView.as_view(), name="HardwareReturn"),
    # path('hardware/return/<int:pk>', views.HardwareReturn, name="HardwareReturn"),
    
    
    path('assignassets', views.AssignedView, name="AssignAsset"),
    # path('unassignassets', UnAssignedView.as_view(), name="UnAssignAsset"),
    
    path('ajax/load-category', views.load_category, name='ajax_load_category'), # AJAX
    path('ajax/load-location', views.load_location, name='ajax_load_location'), # AJAX
    path('ajax/load-emp-location', views.load_emp_location, name='ajax_load_emplocation'), # AJAX
    path('ajax/load-assignuser-location', views.load_assignuser_location, name='ajax_load_assignuserlocation'), # AJAX
    
    
    
    #Reports
    path('hardware_assigned-asset',AssignedAssetReportListView.as_view(), name="AssignedAssetReport"),
    path('hardware_unassigned-asset',UnAssignedAssetReportListView.as_view(), name="UnAssignedAssetReport"),
    path('hardware-disposed-asset', DisposedAssetListView.as_view(), name="DisposedAsset"),
    path('software-in-use', SoftwareInUseListView.as_view(), name="SoftwareInUse"),
    path('software-in-stock', SoftwareInStockListView.as_view(), name="SoftwareInStock"),
    
    path('non-it-assets', views.NonITAssetCreateView, name="NonITAssetCreate"),
    path('non-it-assets-list', NonITAssetListView.as_view(), name="NonITAssetList"),
    path('non-it-assets/update/<int:pk>', NonITAssetUpdateView.as_view(), name="NonITAssetUpdate"),
    # path('hardware/detail/<int:pk>', HardwareDetailView.as_view(), name="HardwareDetail"),
    path('non-it-asset/detail/<int:pk>',views.NonITAssetDetailView, name="NonITAssetDetail"),
    path('non-it-assets/assign/<int:pk>', NonITAssetAssignView.as_view(), name="NonITAssetAssign"),
    # path('hardware/return/<int:pk>', HardwareReturnView.as_view(), name="HardwareReturn"),
    # path('hardware/return/<int:pk>', views.HardwareReturn, name="HardwareReturn"),
]

users/urls.py
from django.urls import path
from users import views
from .views import (
    UserListView,
   
    UserCreateView,
    UserUpdateView,
)


urlpatterns = [

    path('list', UserListView.as_view(), name="UserList"),
    path('add', UserCreateView.as_view(), name="UserCreate"),
    path('<int:pk>/update', UserUpdateView.as_view(), name="UserUpdate"),
    # path('add', views.UserCreateView, name="UserCreate"),
    
    # path('<int:pk>', UserDetailView.as_view(), name="UserDetail"),
    path('<int:pk>', views.UserDetailView, name="UserDetail"),
    
    path('ajax/load-emp-location', views.load_empuser_location, name='ajax_load_empuserlocation'), # AJAX 
]

product/models.py
from django.db import models
from users.models import User
import datetime
from master.models import (Vendor, Location,
                            Category,  Branch, SoftwareType)


# SOFTWARE PRODUCT
class Software(models.Model):
    name = models.CharField(max_length=50)
    softwaretype = models.ForeignKey(SoftwareType, on_delete=models.PROTECT)
    purchased_on = models.DateField((""), auto_now=False, auto_now_add=False)
    expiry = models.DateField((""), auto_now=False, auto_now_add=False)
    installed_on = models.ForeignKey("Hardware", null=True, blank=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.name
    
    


# HARDWARE PRODUCT
class Hardware(models.Model):
    name = models.CharField(max_length=50)
    # brand = models.ForeignKey(Brand, on_delete=models.PROTECT)
    # category = models.ForeignKey(Category, on_delete=models.PROTECT)
    # assettype=models.ForeignKey(Category,on_delete=models.PROTECT,null=True, related_name='asset_type1')
    asset_type=models.CharField(choices= (('IT Assets', 'IT Assets'),('Non IT Assets', 'Non IT Assets')),max_length=50,blank=True,default="IT Assets")
    # category = models.CharField(choices= (('IT Assets', 'IT Assets'),('Non IT Assets', 'Non IT Assets')),max_length=50)
    category = models.ForeignKey(Category, on_delete=models.PROTECT,null=True)
    barcode = models.CharField(max_length=50)
    serial = models.CharField(max_length=50)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT)
    purchased_on = models.DateField(auto_now=False, auto_now_add=False)
    warranty_expiry = models.DateField(auto_now=False, auto_now_add=False)
    tpm_expiry = models.DateField(auto_now=False, auto_now_add=False)
    status = models.CharField(max_length=30, choices=(
        ('working', 'working'), ('damaged', 'damaged'),('disposed', 'disposed')))
    branch= models.ForeignKey(Branch,on_delete=models.PROTECT,null=True)
    location = models.ForeignKey(Location,on_delete=models.PROTECT,null=True)
    assigned_to = models.ForeignKey(User, null=True ,blank=True, on_delete=models.PROTECT)
    cost=models.PositiveIntegerField(blank=True)

    def __str__(self):
        return self.name + " - " + self.barcode
    
    
        
    # def remaining_days(self):
    #     remaining_days = (self.warranty_expiry - self.purchased_on).days
        
    #     years = remaining_days // 365

    #     # Calculating months
    #     months = (remaining_days - years *365) // 30

    #     # Calculating days
    #     days = (remaining_days - years * 365 - months*30)
        
    #     return years,months,days
    #    

    
    
# Non IT Assets model

class Nonitasset(models.Model):
    name = models.CharField(max_length=50)
    asset_type=models.CharField(max_length=50,blank=True,default="NON IT Assets")
    category = models.ForeignKey(Category, on_delete=models.PROTECT,null=True)
    barcode = models.CharField(max_length=50)
    serial = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT)
    purchased_on = models.DateField(auto_now=False, auto_now_add=False)
    warranty_expiry = models.DateField(auto_now=False, auto_now_add=False)
    # status = models.CharField(max_length=30, choices=(
    #     ('working', 'working'), ('damaged', 'damaged'),('disposed', 'disposed')))
    branch= models.ForeignKey(Branch,on_delete=models.PROTECT,null=True)
    location = models.ForeignKey(Location,on_delete=models.PROTECT,null=True)
    assigned_to = models.ForeignKey(User, null=True ,blank=True, on_delete=models.PROTECT)
    cost=models.PositiveIntegerField(blank=True)

    def __str__(self):
        return self.name + " - " + self.barcode

product/templates/product/hardware/hardware_assign.html
{% load crispy_forms_tags %}

<!-- sample modal content -->
    <div id="myModal{{hardware.pk}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title mt-0" id="myModalLabel">Assign Product</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <h5>Assign {{hardware.name}}</h5>
                    {% comment %} id="HardwareCreateForm" data-category-url="{% url 'ajax_load_assignuserlocation' %}" {% endcomment %}
                    
                    <form method="post" name='assign' id="HardwareAssignForm" data-category-url="{% url 'ajax_load_assignuserlocation' %}" >
                        {% csrf_token %}
    
                        {% comment %} <div class="form-row">
                            <div class="form-group">
                                {{form.name|as_crispy_field }}
    
                            </div>
                            <div class="form-group">
                                {{form.brand|as_crispy_field}}
    
                            </div>  
                            <div class="form-group">
                                {{form.category|as_crispy_field}}
    
                            </div>
    
                            <div class="form-group">
                                {{form.subcategory|as_crispy_field}}
    
                            </div>
                            <div class="form-group">
                                {{form.barcode|as_crispy_field}}
    
                            </div>
    
                            <div class="form-group">
                                {{form.serial|as_crispy_field}}
    
                            </div>
    
                           <div class="form-group">
                                {{form.vendor|as_crispy_field}}
    
                            </div> 
    
                            <div class="form-group">
                                {{form.purchased_on|as_crispy_field}}
    
                            </div>
    
                            <div class="form-group">
                                {{form.warranty_expiry|as_crispy_field}}
    
                            </div>
    
                            <div class="form-group">
                                {{form.tpm_expiry|as_crispy_field}}
                        </div>
                        <div class="form-group">
                            {{form.status|as_crispy_field}}
    
                        </div> 
                             {% endcomment %}
                        {% comment %} <div class="form-group">
                                {{form.branch|as_crispy_field}}
    
                        </div>   {% endcomment %}
                        <div class="form-group col-6">
                            {{form.assigned_to|as_crispy_field}}
    
                        </div>
                        
                        <div class="form-group col-6">
                            {{form.location|as_crispy_field}}
                                           </div> 
                                      
    
         
                        
                        
                        {% comment %} <button type="submit" class="btn btn-outline-primary">Submit</button> {% endcomment %}
                  
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Save changes</button>
                </div>
            </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!--script type="text/javascript">
// In your Javascript (external .js resource or <script> tag)
    $(document).change(function () {
        
        $('#id_assigned_to').change(function () {
            
            const url = $('#HardwareCreateForm');  // get the url of the `load_cities` view
            

            const UserId = $(this).val();  // get the selected country ID from the HTML input
            
           
            $.ajax({                                       // initialize an AJAX request
                url: url.attr('data-category-url'),                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'id_assigned_to': UserId       // add the country id to the GET parameters
                },
                
                success: function (data) 
                {   // `data` is the return of the `load_cities` view function
                
                    $("#id_location").html(data);  // replace the contents of the city input with the data that came from the server
                    
                    // {% comment %}                    

                    // let html_data = '<option value=""></option>';
                    // data.forEach(function (city) {
                    //     html_data += `<option value="${city.id}">${city.name}</option>`
                    // });
                    // console.log(html_data);
                    // $('#id_city').html(html_data); {% endcomment %}

                    
                }
            });

        });
});

</script-->


<script type="text/javascript">
    // In your Javascript (external .js resource or <script> tag)
    $(document).ready(function () {

        $('#id_assigned_to').change(function () {

            const url = $('#HardwareAssignForm');  // get the url of the `load_cities` view


            const locationId = $(this).val();  // get the selected country ID from the HTML input

            console.log("working")
            $.ajax({                                       // initialize an AJAX request
                url: url.attr('data-category-url'),                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'userlocation_id': locationId       // add the country id to the GET parameters
                },

                success: function (data) {   // `data` is the return of the `load_cities` view function
                    console.log("working")
                    $("#id_location").html(data);  // replace the contents of the city input with the data that came from the server
                    console.log("working")
                    // {% comment %}                    

                    // let html_data = '<option value="">---------</option>';
                    // data.forEach(function (city) {
                    //     html_data += `<option value="${city.id}">${city.name}</option>`
                    // });
                    // console.log(html_data);
                    // $('#id_city').html(html_data); {% endcomment %}


                }
            });

        });
    });

</script>

product/templates/product/hardware/hardware_create.html
{% extends 'dashboard/index.html' %}
{% load crispy_forms_tags %}
{% block title_add %}
<!-- start page title -->
<div class="row align-items-center">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4 class="font-size-18">Add Hardware Product</h4>
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="javascript: void(0);">Product</a></li>
                <li class="breadcrumb-item"><a href="{% url 'HardwareList' %}">Hardware</a></li>
                <li class="breadcrumb-item active">Add Hardware Product</li>
            </ol>
        </div>
    </div>
    <div class="col-sm-6">

        <button onclick="history.back()" type="button" class="btn btn-primary  w-lg mt-4 mr-4 float-right">Back</button>
    </div>
</div>
<!-- end page title -->

{% endblock title_add %}
{% block body %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="mt-0 header-title"></h4>
                {% comment %} id="HardwareCreateForm" data-category-url="{% url 'ajax_load_category' %}" {% endcomment%}
                <form method="post" id="HardwareCreateForm" data-category-url="{% url 'ajax_load_emplocation' %}">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="form-group col-md-3 mb-0">
                            {{form.name|as_crispy_field}}

                        </div>

                        {% comment %} <div class="form-group col-md-3 mb-0">
                            {{form.asset_type|as_crispy_field}}

                        </div> {% endcomment %}

                        <div class="form-group col-md-3 mb-0">
                            {{form.category|as_crispy_field}}

                        </div>

                        {% comment %} <div class="form-group col-md-3 mb-0">
                            {{form.subcategory|as_crispy_field}}

                        </div> {% endcomment %}
                        <div class="form-group col-md-3 mb-0">
                            {{form.barcode|as_crispy_field}}

                        </div>

                        <div class="form-group col-md-3 mb-0">
                            {{form.serial|as_crispy_field}}

                        </div>

                        <div class="form-group col-md-3 mb-0">
                            {{form.vendor|as_crispy_field}}

                        </div>

                        <div class="form-group col-md-3 mb-0">
                            {{form.purchased_on|as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.cost|as_crispy_field}}

                        </div>

                        <div class="form-group col-md-3 mb-0">
                            {{form.warranty_expiry|as_crispy_field}}

                        </div>

                        <div class="form-group col-md-3 mb-0">
                            {{form.tpm_expiry|as_crispy_field}}
                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.status|as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.branch|as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.location|as_crispy_field}}

                        </div>
                        {% comment %} <div class="form-group col-md-3 mb-0">
                            {{form.assigned_to|as_crispy_field}}

                        </div> {% endcomment %}
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </form>
                {% comment %} {{form.errors}} {% endcomment %}
            </div>
        </div>
    </div>

    <!--script type="text/javascript">
// In your Javascript (external .js resource or <script> tag)
    $(document).ready(function () {
        
        $('#id_category').change(function () {
            
            const url = $('#HardwareCreateForm');  // get the url of the `load_cities` view
            

            const categoryId = $(this).val();  // get the selected country ID from the HTML input
            

            $.ajax({                                       // initialize an AJAX request
                url: url.attr('data-category-url'),                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'category_id': categoryId       // add the country id to the GET parameters
                },
                
                success: function (data) 
                {   // `data` is the return of the `load_cities` view function
                
                    $("#id_subcategory").html(data);  // replace the contents of the city input with the data that came from the server
                    
                    // {% comment %}                    

                    // let html_data = '<option value=""></option>';
                    // data.forEach(function (city) {
                    //     html_data += `<option value="${city.id}">${city.name}</option>`
                    // });
                    // console.log(html_data);
                    // $('#id_city').html(html_data); {% endcomment %}

                    
                }
            });

        });
});

    
</script-->
<script type="text/javascript">
        // In your Javascript (external .js resource or <script> tag)
        $(document).ready(function () {

            $('#id_branch').change(function () {

                const url = $('#HardwareCreateForm');  // get the url of the `load_cities` view


                const branchId = $(this).val();  // get the selected country ID from the HTML input

                console.log("working")
                $.ajax({                                       // initialize an AJAX request
                    url: url.attr('data-category-url'),                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'branch_id': branchId       // add the country id to the GET parameters
                    },

                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        console.log("working")
                        $("#id_location").html(data);  // replace the contents of the city input with the data that came from the server
                        console.log("working")
                        // {% comment %}                    

                        // let html_data = '<option value="">---------</option>';
                        // data.forEach(function (city) {
                        //     html_data += `<option value="${city.id}">${city.name}</option>`
                        // });
                        // console.log(html_data);
                        // $('#id_city').html(html_data); {% endcomment %}


                    }
                });

            });
        });

    </script>
        {% endblock body %}

product/templates/product/hardware/hardware_returninstock.html
{% load crispy_forms_tags %}

<!-- sample modal content -->
    <div id="myModalreturn{{hardware.pk}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title mt-0" id="myModalLabel">Return Product</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <h5>Return{{hardware.name}}</h5>
                    {% comment %} id="HardwareCreateForm" data-category-url="{% url 'ajax_load_assignuserlocation' %}" {% endcomment %}
                    
                    <form method="post" id="HardwareReturnForm" data-category-url="{% url 'ajax_load_emplocation' %}" >
                        {% csrf_token %}
    
                             <div class="form-group">
                                {{form2.branch|as_crispy_field}}
    
                            </div>  
                        <div class="form-group ">
                            {{form2.location|as_crispy_field}}
                        </div> 
                                      
    
         
                         
                  
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Save changes</button>
                </div>
            </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

   
    {% comment %} {% block javascript %} {% endcomment %}

 <!--script type="text/javascript">
        // In your Javascript (external .js resource or <script> tag)
        $(document).ready(function () {
            console.log("function started")
            $('#id_branch').change(function () {
                
                console.log("branch id fetched")
                const url = $('#HardwareReturnForm');  // get the url of the `load_cities` view
                console.log("form fetched")

                const branchId = $(this).val();  // get the selected country ID from the HTML input

                console.log("working")
                $.ajax({                                       // initialize an AJAX request
                    url: url.attr('data-category-url'),                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {

                        csrfmiddlewaretoken:'{{ csrf_token }}',
                        'branch_id': branchId       // add the country id to the GET parameters
                    },

                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        console.log(data)
                        $("#id_location").html(data);  // replace the contents of the city input with the data that came from the server
                        console.log("working")
                        // {% comment %}                    

                        // let html_data = '<option value="">---------</option>';
                        // data.forEach(function (city) {
                        //     html_data += `<option value="${city.id}">${city.name}</option>`
                        // });
                        // console.log(html_data);
                        // $('#id_city').html(html_data); {% endcomment %}


                    }
                });

            });
        });

    </script-->
    <script type="text/javascript">
        // In your Javascript (external .js resource or <script> tag)
            $(document).ready(function () {
                
                $('#id_branch').change(function () {
                    
                    const url = $('#HardwareReturnForm');  // get the url of the `load_cities` view
                        
                    const branchId = $(this).val();  // get the selected country ID from the HTML input
                    console.log("working")
                    $.ajax({                                       // initialize an AJAX request
                        url: url.attr('data-category-url'),                    // set the url of the request (= /persons/ajax/load-cities/ )
                        data: {
                            'branch_id': branchId       // add the country id to the GET parameters
                        },
                        
                        success: function (data) 
                        {   // `data` is the return of the `load_cities` view function
                            console.log(data)
                            $("#id_location").html(data);  // replace the contents of the city input with the data that came from the server
                            console.log("working")
                            // {% comment %}                    
        
                            // let html_data = '<option value="">---------</option>';
                            // data.forEach(function (city) {
                            //     html_data += `<option value="${city.id}">${city.name}</option>`
                            // });
                            // console.log(html_data);
                            // $('#id_city').html(html_data); {% endcomment %}
        
                            
                        }
                    });
        
                });
        });
        
            
        </script>
    </body>

    {% comment %} {% endblock javascript %} {% endcomment %}