asset_management/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LoginPage, name="Login"),
    path('logout/', views.LogoutUser, name="Logout"),
    path('user/', include('users.urls')),
    path('master/', include('master.urls')),
    path('product/', include('product.urls')),
    path('dashboard/', views.Dashboard,name='Dashboard'),
]

product/urls.py
from django.urls import path
from users import views
from product import views

from .views import (SoftwareCreateView, SoftwareListView,
                    HardwareListView,SoftwareUpdateView,HardwareUpdateView,HardwareAssignView,
                    HardwareDetailView,AssignedAssetReportListView,UnAssignedAssetReportListView,
                    DisposedAssetListView,SoftwareInUseListView,SoftwareInStockListView,NonITAssetListView,
NonITAssetUpdateView,NonITAssetAssignView,
# UnAssignedView,
)

urlpatterns = [
    path('software', SoftwareCreateView.as_view(), name="SoftwareCreate"),
    path('software_list', SoftwareListView.as_view(), name="SoftwareList"),
    path('software/update/<int:pk>', SoftwareUpdateView.as_view(), name="SoftwareUpdate"),
    
    
    path('hardware', views.HardwareCreateView, name="HardwareCreate"),
    path('hardware_list', HardwareListView.as_view(), name="HardwareList"),
    path('hardware/update/<int:pk>', HardwareUpdateView.as_view(), name="HardwareUpdate"),
    # path('hardware/detail/<int:pk>', HardwareDetailView.as_view(), name="HardwareDetail"),
    path('hardware/detail/<int:pk>', views.HardwareDetailView, name="HardwareDetail"),
    path('hardware/assign/<int:pk>', HardwareAssignView.as_view(), name="HardwareAssign"),
    # path('hardware/return/<int:pk>', HardwareReturnView.as_view(), name="HardwareReturn"),
    # path('hardware/return/<int:pk>', views.HardwareReturn, name="HardwareReturn"),
    
    
    path('assignassets', views.AssignedView, name="AssignAsset"),
    # path('unassignassets', UnAssignedView.as_view(), name="UnAssignAsset"),
    
    path('ajax/load-category', views.load_category, name='ajax_load_category'), # AJAX
    path('ajax/load-location', views.load_location, name='ajax_load_location'), # AJAX
    path('ajax/load-emp-location', views.load_emp_location, name='ajax_load_emplocation'), # AJAX
    path('ajax/load-assignuser-location', views.load_assignuser_location, name='ajax_load_assignuserlocation'), # AJAX
    
    
    
    #Reports
    path('hardware_assigned-asset',AssignedAssetReportListView.as_view(), name="AssignedAssetReport"),
    path('hardware_unassigned-asset',UnAssignedAssetReportListView.as_view(), name="UnAssignedAssetReport"),
    path('hardware-disposed-asset', DisposedAssetListView.as_view(), name="DisposedAsset"),
    path('software-in-use', SoftwareInUseListView.as_view(), name="SoftwareInUse"),
    path('software-in-stock', SoftwareInStockListView.as_view(), name="SoftwareInStock"),
    
    path('non-it-assets', views.NonITAssetCreateView, name="NonITAssetCreate"),
    path('non-it-assets-list', NonITAssetListView.as_view(), name="NonITAssetList"),
    path('non-it-assets/update/<int:pk>', NonITAssetUpdateView.as_view(), name="NonITAssetUpdate"),
    # path('hardware/detail/<int:pk>', HardwareDetailView.as_view(), name="HardwareDetail"),
    path('non-it-asset/detail/<int:pk>',views.NonITAssetDetailView, name="NonITAssetDetail"),
    path('non-it-assets/assign/<int:pk>', NonITAssetAssignView.as_view(), name="NonITAssetAssign"),
    # path('hardware/return/<int:pk>', HardwareReturnView.as_view(), name="HardwareReturn"),
    # path('hardware/return/<int:pk>', views.HardwareReturn, name="HardwareReturn"),
]

users/urls.py
from django.urls import path
from users import views
from .views import (
    UserListView,
   
    UserCreateView,
    UserUpdateView,
)


urlpatterns = [

    path('list', UserListView.as_view(), name="UserList"),
    path('add', UserCreateView.as_view(), name="UserCreate"),
    path('<int:pk>/update', UserUpdateView.as_view(), name="UserUpdate"),
    # path('add', views.UserCreateView, name="UserCreate"),
    
    # path('<int:pk>', UserDetailView.as_view(), name="UserDetail"),
    path('<int:pk>', views.UserDetailView, name="UserDetail"),
    
    path('ajax/load-emp-location', views.load_empuser_location, name='ajax_load_empuserlocation'), # AJAX 
]

product/models.py
from django.db import models
from users.models import User
import datetime
from master.models import (Vendor, Location,
                            Category,  Branch, SoftwareType)


# SOFTWARE PRODUCT
class Software(models.Model):
    name = models.CharField(max_length=50)
    softwaretype = models.ForeignKey(SoftwareType, on_delete=models.PROTECT)
    purchased_on = models.DateField((""), auto_now=False, auto_now_add=False)
    expiry = models.DateField((""), auto_now=False, auto_now_add=False)
    installed_on = models.ForeignKey("Hardware", null=True, blank=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.name
    
    


# HARDWARE PRODUCT
class Hardware(models.Model):
    name = models.CharField(max_length=50)
    # brand = models.ForeignKey(Brand, on_delete=models.PROTECT)
    # category = models.ForeignKey(Category, on_delete=models.PROTECT)
    # assettype=models.ForeignKey(Category,on_delete=models.PROTECT,null=True, related_name='asset_type1')
    asset_type=models.CharField(choices= (('IT Assets', 'IT Assets'),('Non IT Assets', 'Non IT Assets')),max_length=50,blank=True,default="IT Assets")
    # category = models.CharField(choices= (('IT Assets', 'IT Assets'),('Non IT Assets', 'Non IT Assets')),max_length=50)
    category = models.ForeignKey(Category, on_delete=models.PROTECT,null=True)
    barcode = models.CharField(max_length=50)
    serial = models.CharField(max_length=50)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT)
    purchased_on = models.DateField(auto_now=False, auto_now_add=False)
    warranty_expiry = models.DateField(auto_now=False, auto_now_add=False)
    tpm_expiry = models.DateField(auto_now=False, auto_now_add=False)
    status = models.CharField(max_length=30, choices=(
        ('working', 'working'), ('damaged', 'damaged'),('disposed', 'disposed')))
    branch= models.ForeignKey(Branch,on_delete=models.PROTECT,null=True)
    location = models.ForeignKey(Location,on_delete=models.PROTECT,null=True)
    assigned_to = models.ForeignKey(User, null=True ,blank=True, on_delete=models.PROTECT)
    cost=models.PositiveIntegerField(blank=True)

    def __str__(self):
        return self.name + " - " + self.barcode
    
    
        
    # def remaining_days(self):
    #     remaining_days = (self.warranty_expiry - self.purchased_on).days
        
    #     years = remaining_days // 365

    #     # Calculating months
    #     months = (remaining_days - years *365) // 30

    #     # Calculating days
    #     days = (remaining_days - years * 365 - months*30)
        
    #     return years,months,days
    #    

    
    
# Non IT Assets model

class Nonitasset(models.Model):
    name = models.CharField(max_length=50)
    asset_type=models.CharField(max_length=50,blank=True,default="NON IT Assets")
    category = models.ForeignKey(Category, on_delete=models.PROTECT,null=True)
    barcode = models.CharField(max_length=50)
    serial = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT)
    purchased_on = models.DateField(auto_now=False, auto_now_add=False)
    warranty_expiry = models.DateField(auto_now=False, auto_now_add=False)
    # status = models.CharField(max_length=30, choices=(
    #     ('working', 'working'), ('damaged', 'damaged'),('disposed', 'disposed')))
    branch= models.ForeignKey(Branch,on_delete=models.PROTECT,null=True)
    location = models.ForeignKey(Location,on_delete=models.PROTECT,null=True)
    assigned_to = models.ForeignKey(User, null=True ,blank=True, on_delete=models.PROTECT)
    cost=models.PositiveIntegerField(blank=True)

    def __str__(self):
        return self.name + " - " + self.barcode

product/templates/product/software/software_create.html
{% extends 'dashboard/index.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="mt-0 header-title"></h4>

                <form method="post">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="form-group col-md-3 mb-0">
                            {{form.name|as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.softwaretype|as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.installed_on|as_crispy_field}}

                        </div>
                        
                        <div class="form-group col-md-3 mb-0">
                            <label class=" requiredField">
                                Purchased on<span class="asteriskField">*</span>
                            </label>
                            {{form.purchased_on |as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            <label class=" requiredField">
                                Valid Till<span class="asteriskField">*</span>
                            </label>
                            {{form.expiry|as_crispy_field}}
                    </div>
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </form>
                {% comment %} {{form.errors}} {% endcomment %}
        </div>
    </div>
</div>

<script type="text/javascript">
// In your Javascript (external .js resource or <script> tag)
    $(document).ready(function() {
        $('#id_softwaretype').select2();
    });

</script>
{% endblock body %}

product/templates/product/software/software_instock_list.html
{% extends 'dashboard/index.html' %}
{% block title_add %}
                        <!-- start page title -->
                        <div class="row align-items-center">
                          <div class="col-sm-6">
                              <div class="page-title-box">
                                  <h4 class="font-size-18">Software List</h4>
                                  <ol class="breadcrumb mb-0">
                                      <li class="breadcrumb-item"><a href="javascript: void(0);">Product</a></li>
                                      <li class="breadcrumb-item"><a href="javascript: void(0);">Software</a></li>
                                      <li class="breadcrumb-item active">Software List</li>
                                  </ol>
                              </div>
                          </div>
                          <div class="col-sm-6">

                          
                      </div>     
                    </div>     
                      <!-- end page title -->

{% endblock title_add %}
{% block body %}

<div class="row">
    <div class="col-12">
        {% for message in messages %}
        <div class="alert  alert-outline-success text-gradient-success mb-0" role="alert">
            <strong>{{message}}</strong>
        </div>  
        {% endfor %}
        <div class="card">

            <div class="card-body">
                <div class = " col-md-2 mb-2 ml-auto">
                <a href="{% url 'SoftwareCreate' %}"><button type="button" class=" btn btn-outline-purple btn-lg btn-block">Add Software</button>
                </a></div>

                <table id="datatable-buttons" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Software Type</th>
                        <th>Purchased On</th>
                        <th>Expiry</th>
                        <th>Installed on</th>
                        {% comment %} <th>Action</th> {% endcomment %}
                        
                    </tr>
                    </thead>


                    <tbody>
                        {% for software in software  %}
                    <tr>
                        <td>{{software.name}}</td>
                        <td>{{software.softwaretype}}</td>
                        <td>{{software.purchased_on}}</td>
                        <td>{{software.expiry}}</td>
                        <td>{{software.installed_on}}</td>
                        
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

{% endblock body %}

product/templates/product/software/software_inuse_list.html
{% extends 'dashboard/index.html' %}
{% block title_add %}
                        <!-- start page title -->
                        <div class="row align-items-center">
                          <div class="col-sm-6">
                              <div class="page-title-box">
                                  <h4 class="font-size-18">Software List</h4>
                                  <ol class="breadcrumb mb-0">
                                      <li class="breadcrumb-item"><a href="javascript: void(0);">Product</a></li>
                                      <li class="breadcrumb-item"><a href="javascript: void(0);">Software</a></li>
                                      <li class="breadcrumb-item active">Software List</li>
                                  </ol>
                              </div>
                          </div>
                          <div class="col-sm-6">

                          
                      </div>     
                    </div>     
                      <!-- end page title -->

{% endblock title_add %}
{% block body %}

<div class="row">
    <div class="col-12">
        {% for message in messages %}
        <div class="alert  alert-outline-success text-gradient-success mb-0" role="alert">
            <strong>{{message}}</strong>
        </div>  
        {% endfor %}
        <div class="card">

            <div class="card-body">
                <div class = " col-md-2 mb-2 ml-auto">
                <a href="{% url 'SoftwareCreate' %}"><button type="button" class=" btn btn-outline-purple btn-lg btn-block">Add Software</button>
                </a></div>

                <table id="datatable-buttons" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Software Type</th>
                        <th>Purchased On</th>
                        <th>Expiry</th>
                        <th>Installed on</th>
                        {% comment %} <th>Action</th> {% endcomment %}
                        
                    </tr>
                    </thead>


                    <tbody>
                        {% for software in software  %}
                    <tr>
                        <td>{{software.name}}</td>
                        <td>{{software.softwaretype}}</td>
                        <td>{{software.purchased_on}}</td>
                        <td>{{software.expiry}}</td>
                        <td>{{software.installed_on}}</td>
                        {% comment %} <td> 
                            <a href="{% url 'SoftwareUpdate' software.pk %}">       
                                <button type="button" class="btn btn-sm btn-success">Edit</button>
                              </a>
                        </td> {% endcomment %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

{% endblock body %}

product/templates/product/software/software_list.html
{% extends 'dashboard/index.html' %}
{% block title_add %}
                        <!-- start page title -->
                        <div class="row align-items-center">
                          <div class="col-sm-6">
                              <div class="page-title-box">
                                  <h4 class="font-size-18">Software List</h4>
                                  <ol class="breadcrumb mb-0">
                                      <li class="breadcrumb-item"><a href="javascript: void(0);">Product</a></li>
                                      <li class="breadcrumb-item"><a href="javascript: void(0);">Software</a></li>
                                      <li class="breadcrumb-item active">Software List</li>
                                  </ol>
                              </div>
                          </div>
                          <div class="col-sm-6">

                          <a href="{% url 'SoftwareCreate' %}">
                            <button type="button" class="btn btn-primary  w-lg mt-4 mr-4 float-right">Add Software </button>
                            </a>
                      </div>     
                    </div>     
                      <!-- end page title -->

{% endblock title_add %}
{% block body %}

<div class="row">
    <div class="col-12">
        {% for message in messages %}
        <div class="alert  alert-outline-success text-gradient-success mb-0" role="alert">
            <strong>{{message}}</strong>
        </div>  
        {% endfor %}
        <div class="card">

            <div class="card-body">
                <div class = " col-md-2 mb-2 ml-auto">
                <a href="{% url 'SoftwareCreate' %}"><button type="button" class=" btn btn-outline-purple btn-lg btn-block">Add Software</button>
                </a></div>

                <table id="software" class="table table-striped" >
                    
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Software Type</th>
                        <th>Purchased On</th>
                        <th>Expiry</th>
                        <th>Installed on</th>
                        {% comment %} <th>Action</th> {% endcomment %}
                        
                    </tr>
                    </thead>


                    <tbody>
                        {% for software in software  %}
                    <tr>
                        <td><a href="{% url 'SoftwareUpdate' software.pk %}">{{software.name}}</a></td>
                        <td>{{software.softwaretype}}</td>
                        <td>{{software.purchased_on}}</td>
                        <td>{{software.expiry}}</td>
                        <td>{{software.installed_on}}</td>
                        {% comment %} <td> 
                            <a href="{% url 'SoftwareUpdate' software.pk %}">       
                                <button type="button" class="btn btn-sm btn-success">Edit</button>
                              </a>
                        </td> {% endcomment %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

{% endblock body %}

product/templates/product/software/software_update.html
{% extends 'dashboard/index.html' %}
{% load crispy_forms_tags %}
{% block title_add %}
                        <!-- start page title -->
                        <div class="row align-items-center">
                          <div class="col-sm-6">
                              <div class="page-title-box">
                                  <h4 class="font-size-18">Edit Software: {{software.name | title}} </h4>
                                  <ol class="breadcrumb mb-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);">Product</a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'SoftwareList' %}">Software</a></li>
                                    <li class="breadcrumb-item active">Edit Software: {{software.name | title}} </li>
                                  </ol>
                              </div>
                          </div>
                          <div class="col-sm-6">

                            <button onclick="history.back()" type="button" class="btn btn-primary  w-lg mt-4 mr-4 float-right">Back</button>
                      </div>     
                    </div>     
                      <!-- end page title -->

{% endblock title_add %}
{% block body %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="mt-0 header-title"></h4>

                <form method="post">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="form-group col-md-3 mb-0">
                            {{form.name|as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.softwaretype|as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{form.installed_on|as_crispy_field}}

                        </div>
                        
                        <div class="form-group col-md-3 mb-0">
                            <label class=" requiredField">
                                Purchased on<span class="asteriskField">*</span>
                            </label>
                            {{form.purchased_on |as_crispy_field}}

                        </div>
                        <div class="form-group col-md-3 mb-0">
                            <label class=" requiredField">
                                Valid Till<span class="asteriskField">*</span>
                            </label>
                            {{form.expiry|as_crispy_field}}
                    </div>
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </form>
                {% comment %} {{form.errors}} {% endcomment %}
        </div>
    </div>
</div>

<script type="text/javascript">
// In your Javascript (external .js resource or <script> tag)
    $(document).ready(function() {
        $('#id_softwaretype').select2();
    });

</script>
{% endblock body %}